### ISSUE TITLE
CalledProcessError caused by subprocess from tabula.py (or pyinstaller)

### ISSUE THREAD

**Issue by Ichiroad** [Ichiroad/tabulapy#1]
I got a error below. How can I solve it ? The script works well on the pycharm but it doesn't work on .exe created by pyinstaller with using ">pyinstaller --onefile GetPdfTable.py" command. The line 91 in GetPdfTable.py is "tabula.read_pdf(file, lattice=True, pages=str(page))" which call subprocess module??.
And I'm using:
pyinstaller: 4.2
tabula-py: 2.2.0
tabula: 1.0.5

I tried:
-other pdf files
--> same error
-version down (tabula-py: 1.4.1, tabula: 1.03)
--> same error

----error on console----
Error from tabula-java:
Error: Unable to access jarfile C:\Users\AAAA\AppData\Local\Temp_MEI174282\tabula\tabula-1.0.4-jar-with-dependencies.jar

Exception in Tkinter callback
Traceback (most recent call last):
File "tkinter_init_.py", line 1885, in call
File "GetPdfTable.py", line 91, in button_click
File "tabula\io.py", line 322, in read_pdf
File "tabula\io.py", line 80, in _run
File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['java', '-Dfile.encoding=UTF8', '-jar', 'C:\Users\AAAA\AppData\Local\Temp\_MEI174282\tabula\tabula-1.0.4-jar-with-dependencies.jar', '--pages', '1', '--lattice', '--guess', '--format', 'JSON', 'C:/Users/AAAA/OneDrive/Documents/pythonProject/test.pdf']' returned non-zero exit status 1.

#https://github.com/chezou/tabula-py/issues/169

I'm a beginner of Python and hope your kindness.
Best regards,
Ichiroad

#tabula-py
#pyinstaller

**Comment by Ichiroad** [comment]
Finally, this bug was not able to be solved in my current knowledge, As a workaround, I'll try Camelot module to get PDF table.
